meteor:
  dockerfile: Dockerfile
  build: .
  environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo/yourapp
      - ROOT_URL=http://example.com
  ports:
    - 3000:3000
  links:
   - mongo

mongo:
  image: mongo:latest